                <option value="Sin Imputacion">1 - Sin Imputacion</option>
                <option value="Gastos de Explot">2 - Gastos de Explot</option>
                <option value="Bienes de Uso">3 - Bienes de Uso</option>
                <option value="Com.y Lubricant.">4 - Com.y Lubricant.</option>
                <option value="Seguros">5 - Seguros</option>
                <option value="Alquiler">6 - Alquiler</option>
                <option value="Peaje">7 - Peaje</option>
                <option value="Gas Oil">8 - Gas Oil</option>
                <option value="Vtas.Consu.Final">9 - Vtas.Consu.Final</option>
                <option value="Vtas.RI.y Ext.">10 - Vtas.RI.y Ext.</option>
                <option value="Vtas.CF IVA 10,5">11 - Vtas.CF IVA 10,5</option>
                <option value="Vtas.RI IVA 10,5">12 - Vtas.RI IVA 10,5</option>
                <option value="Vtas.CF Gomeria">13 - Vtas.CF Gomeria</option>
                <option value="Vtas.RI Gomeria">14 - Vtas.RI Gomeria</option>
                <option value="Vtas.CF Lavadero">15 - Vtas.CF Lavadero</option>
                <option value="Vtas.RI Lavadero">16 - Vtas.RI Lavadero</option>
                <option value="Vtas.CF Mecanico">17 - Vtas.CF Mecanico</option>
                <option value="Vtas.RI Mecanico">18 - Vtas.RI Mecanico</option>
                <option value="Monotributo">19 - Monotributo</option>
                <option value="Ipt.Deb.Ley25413">20 - Ipt.Deb.Ley25413</option>
                <option value="Cpras.DGR Bs.As.">21 - Cpras.DGR Bs.As.</option>
                <option value="Comisiones">22 - Comisiones</option>
                <option value="Gastos Bancarios">23 - Gastos Bancarios</option>
                <option value="Vtas.Cielo.R.I.">24 - Vtas.Cielo.R.I.</option>
                <option value="Vtas.Cielo.C.F.">25 - Vtas.Cielo.C.F.</option>
                <option value="Ropa de Trabajo">26 - Ropa de Trabajo</option>
                <option value="Vtas.Chaco">27 - Vtas.Chaco</option>
                <option value="Insumos">28 - Insumos</option>
                <option value="Pago de Premios">29 - Pago de Premios</option>
                <option value="Comision IPLYC">30 - Comision IPLYC</option>
                <option value="Ingresos Cap.Fed">31 - Ingresos Cap.Fed</option>
                <option value="Medicina Prepaga">32 - Medicina Prepaga</option>
                <option value="Fletes Bs.As">33 - Fletes Bs.As</option>
                <option value="Fletes Cordoba">34 - Fletes Cordoba</option>
                <option value="Fletes Corrientes">35 - Fletes Corrientes</option>
                <option value="Fletes Chaco">36 - Fletes Chaco</option>
                <option value="Fletes Misiones">37 - Fletes Misiones</option>
                <option value="Fletes Rio Negro">38 - Fletes Rio Negro</option>
                <option value="Fletes Santa Fe">39 - Fletes Santa Fe</option>
                <option value="Fletes Tucuman">40 - Fletes Tucuman</option>
                <option value="Fletes del Ext.">41 - Fletes del Ext.</option>
                <option value="Honor.Medicos">42 - Honor.Medicos</option>
                <option value="Fletes Chubut">43 - Fletes Chubut</option>
                <option value="Fletes Formosa">44 - Fletes Formosa</option>
                <option value="Fletes Salta">45 - Fletes Salta</option>
                <option value="Flete Sgo.Estero">46 - Flete Sgo.Estero</option>
                <option value="Cpra.DGR Rio Neg">47 - Cpra.DGR Rio Neg</option>
                <option value="Honorarios Prof.">48 - Honorarios Prof.</option>