                <option value="1">1 - Sin Imputacion</option>
                <option value="2">2 - Gastos de Explot</option>
                <option value="3">3 - Bienes de Uso</option>
                <option value="4">4 - Com.y Lubricant.</option>
                <option value="5">5 - Seguros</option>
                <option value="6">6 - Alquiler</option>
                <option value="7">7 - Peaje</option>
                <option value="8">8 - Gas Oil</option>
                <option value="9">9 - Vtas.Consu.Final</option>
                <option value="10">10 - Vtas.RI.y Ext.</option>
                <option value="11">11 - Vtas.CF IVA 10,5</option>
                <option value="12">12 - Vtas.RI IVA 10,5</option>
                <option value="13">13 - Vtas.CF Gomeria</option>
                <option value="14">14 - Vtas.RI Gomeria</option>
                <option value="15">15 - Vtas.CF Lavadero</option>
                <option value="16">16 - Vtas.RI Lavadero</option>
                <option value="17">17 - Vtas.CF Mecanico</option>
                <option value="18">18 - Vtas.RI Mecanico</option>
                <option value="19">19 - Monotributo</option>
                <option value="20">20 - Ipt.Deb.Ley25413</option>
                <option value="21">21 - Cpras.DGR Bs.As.</option>
                <option value="22">22 - Comisiones</option>
                <option value="23">23 - Gastos Bancarios</option>
                <option value="24">24 - Vtas.Cielo.R.I.</option>
                <option value="25">25 - Vtas.Cielo.C.F.</option>
                <option value="26">26 - Ropa de Trabajo</option>
                <option value="27">27 - Vtas.Chaco</option>
                <option value="28">28 - Insumos</option>
                <option value="29">29 - Pago de Premios</option>
                <option value="30">30 - Comision IPLYC</option>
                <option value="31">31 - Ingresos Cap.Fed</option>
                <option value="32">32 - Medicina Prepaga</option>
                <option value="33">33 - Fletes Bs.As</option>
                <option value="34">34 - Fletes Cordoba</option>
                <option value="35">35 - Fletes Corrientes</option>
                <option value="36">36 - Fletes Chaco</option>
                <option value="37">37 - Fletes Misiones</option>
                <option value="38">38 - Fletes Rio Negro</option>
                <option value="39">39 - Fletes Santa Fe</option>
                <option value="40">40 - Fletes Tucuman</option>
                <option value="41">41 - Fletes del Ext.</option>
                <option value="42">42 - Honor.Medicos</option>
                <option value="43">43 - Fletes Chubut</option>
                <option value="44">44 - Fletes Formosa</option>
                <option value="45">45 - Fletes Salta</option>
                <option value="46">46 - Flete Sgo.Estero</option>
                <option value="47">47 - Cpra.DGR Rio Neg</option>
                <option value="48">48 - Honorarios Prof.</option>