<?php
$CUIT="";
$ID="";
$CUIT="";
$nombre="";
$IVA="";
$tablaT="";
$total="";

$ID=$_POST['ID'];
$comprobante=$_POST['comprobante'];
$procesamiento=$_POST['procesamiento'];
$movimiento=$_POST['movimiento'];
$TImputacion=$_POST['TImputacion'];
$TImputacion2=$_POST['TImputacion2'];
$TComprobante=$_POST['TComprobante'];
$NComprobante=$_POST['NComprobante'];
$neto21=$_POST['neto21'];
$neto10y5=$_POST['neto10y5'];
$neto27=$_POST['neto27'];
$ConcNoAgra=$_POST['ConcNoAgra'];
$PercIVA=$_POST['PercIVA'];
$PercDGR=$_POST['PercDGR'];
$PercMuni=$_POST['PercMuni'];
?>