<option value="Ticket">1 - Ticket</option>
<option value="Factura">2 - Factura</option>
<option value="N.Credito">3 - N.Credito</option>
<option value="N.Debito">4 - N.Debito</option>
<option value="Recibo">5 - Recibo</option>
<option value="Liquidaciones">6 - Liquidaciones</option>
<option value="Carta de Porte">7 - Carta de Porte</option>
<option value="Sin Comprobantes">8 - Sin Comprobantes</option>
<option value="Retencion">9 - Retencion</option>